services:
  app:
    image: a12c4g/chaos-simulator-alpine:latest
    container_name: chaos-simulator
    ports:
      - "80:80"
    # volumes:
    #   - chemin-vers-le-.sqlite:/var/www/html/database
    restart: unless-stopped